
spring:
  data:
    mongodb:
      host=localhost
      port=27017
      database=bocky-call-db

server:
  port=9021

spring:
  servlet:
    multipart:
      max-file-size=10MB
      max-request-size=10MB