server:
  port: 8080

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        id: catalogo-servicio
        uri: lb://catalogo-servicio
        predicates:
          Path=/api/catalogo/**
